apiVersion: v1
kind: Secret
metadata:
  name: private-repo-creds
  namespace: default
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: {{.Values.repository_url}}
  sshPrivateKey: {{.Values.repository_key | quote}}